### ISSUE TITLE
parent_id send from client alway 0

### ISSUE THREAD

**Issue by LQTam** [efectn/laravel-menu-builder#2]
**INIT**
![initial](https://user-images.githubusercontent.com/43690329/170821594-cb26ae49-9355-4894-9ad8-2de1a05b9d0a.png)
![initial1](https://user-images.githubusercontent.com/43690329/170821597-c3e7d785-d5ae-494e-83d8-e1c93061b562.png)

**After Added**
![whenadded](https://user-images.githubusercontent.com/43690329/170821624-56e78b06-ba8c-4181-9b78-65b8ada4e8ce.png)
![whenadded1](https://user-images.githubusercontent.com/43690329/170821628-713aef01-7813-4c21-a252-decc1356147f.png)

**Edited also the same as add**

**Comment by efectn** [comment]
@LQTam really sorry for delay. I'll check the issue when i'm free. If you have time, you can create a PR to fix it.

**Comment by perochak** [comment]
@LQTam check my pull request https://github.com/efectn/laravel-menu-builder/pull/6
